### ISSUE TITLE
Enrique Matos 	 Attachments11:19 AM (5 hours ago) 	 to me     View original message RuntimeError: The expanded size of the tensor (4096) must match the existing size (514) at non-singleton dimension 1. Target sizes: [1, 4096]. Tensor sizes: [1, 514] 

### ISSUE THREAD

**Issue by gardero** [ccdv-ai/convert_checkpoint_to_lsg#7]
Hi there
I am having trouble converting a BERTA model to  LSG,
Here I have a link to a notebook.
Can you have a look and give me some hints on why this is not working?
https://colab.research.google.com/drive/1AAxk42ZzELrKdyE-I_HDiuNHVz1rfy4m?usp=sharing

**Comment by ccdv-ai** [comment]
hi @gardero 

You're right, the positional embeddings aren't updated for some reasons. 
I need to investigate.
You can try this piece of code instead in colab:

```
!pip install transformers
!git clone https://github.com/ccdv-ai/convert_checkpoint_to_lsg.git

!python /content/convert_checkpoint_to_lsg/convert_checkpoint.py \
  --initial_model "huggingface/CodeBERTa-language-id" \
  --model_name "lsg-codeBERTa" \
  --architecture RobertaForSequenceClassification \
  --max_sequence_length 4096

from transformers import AutoModelForSequenceClassification, AutoTokenizer
model = AutoModelForSequenceClassification.from_pretrained("lsg-codeBERTa", trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained("lsg-codeBERTa", trust_remote_code=True)
```

Edit: Looks like the model need to be saved and reloaded for the positional embeddings to be updated.

**Comment by gardero** [comment]
Thanks for the response. Indeed, after saving the model and tokenizer and loading them again, the long sequences are supported as expected. 
I guess this can be added to the documentation...
Great work, by the way.
